version: '3.9'
services:
# Este servicio se comenta para levantar únicamente la infra necesaria para desarollar MALSIN desde el STS o cualquier otro IDE..
#  malsin-backend:
#    build: .
#    depends_on:
#      - malsin-postgres
#      - malsin-rabbitmq
#    ports:
#      -  "8070:8080"
#    networks:
#      malsin-network:
#        ipv4_address: 172.168.0.2

  malsin-postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: malsin
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    ports:
    - 5432:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    networks:
      malsin-network:
        ipv4_address: 172.168.0.10
        
  malsin-adminer:
    image: adminer
    restart: always
    ports:
    - 8087:8080
    depends_on:
    - malsin-postgres
        
  malsin-rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
#    environment:  
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER} -- guest -- por defecto
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS} -- guest -- por defecto
    ports:
    - 4369:4369
    - 5671-5672:5671-5672
    - 15671-15672:15671-15672
    - 15691-15692:15691-15692
    - 25672:25672
    networks:
      malsin-network:
        ipv4_address: 172.168.0.12
  malsin-netdata:
    image: netdata/netdata:latest
    ports:
    - 19999:19999
    depends_on:
    - malsin-postgres
    - malsin-rabbitmq
    networks:
      malsin-network:
        ipv4_address: 172.168.0.13
networks:
  malsin-network:
    ipam:
      driver: default
      config:
      - subnet: 172.168.0.0/24