package es.bgtiban.infrastructure.persistence.jpa.entity;
// Generated 6 sept 2022 12:48:20 by Hibernate Tools 5.2.13.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuentas generated by hbm2java
 */
@Entity
@Table(name = "cuentas")
public class Cuentas implements java.io.Serializable {

    private String id;
    private Date fechaAlta;
    private Set peticionesRelCuentases = new HashSet(0);

    public Cuentas() {
    }

    public Cuentas(String id, Date fechaAlta) {
        this.id = id;
        this.fechaAlta = fechaAlta;
    }

    public Cuentas(String id, Date fechaAlta, Set peticionesRelCuentases) {
        this.id = id;
        this.fechaAlta = fechaAlta;
        this.peticionesRelCuentases = peticionesRelCuentases;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false, length = 50)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_alta", nullable = false, length = 29)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }

    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentas")
    public Set getPeticionesRelCuentases() {
        return this.peticionesRelCuentases;
    }

    public void setPeticionesRelCuentases(Set peticionesRelCuentases) {
        this.peticionesRelCuentases = peticionesRelCuentases;
    }

}
