package es.bgtiban.infrastructure.persistence.jpa.entity;
// Generated 6 sept 2022 12:48:20 by Hibernate Tools 5.2.13.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name = "estados")
public class Estados implements java.io.Serializable {

    private int id;
    private String nombre;
    private Set historicoPeticioneses = new HashSet(0);

    public Estados() {
    }

    public Estados(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Estados(int id, String nombre, Set historicoPeticioneses) {
        this.id = id;
        this.nombre = nombre;
        this.historicoPeticioneses = historicoPeticioneses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nombre", nullable = false, length = 10)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
    public Set getHistoricoPeticioneses() {
        return this.historicoPeticioneses;
    }

    public void setHistoricoPeticioneses(Set historicoPeticioneses) {
        this.historicoPeticioneses = historicoPeticioneses;
    }

}
