package es.bgtiban.infrastructure.persistence.jpa.entity;
// Generated 6 sept 2022 12:48:20 by Hibernate Tools 5.2.13.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HistoricoPeticiones generated by hbm2java
 */
@Entity
@Table(name = "historico_peticiones")
public class HistoricoPeticiones implements java.io.Serializable {

    private int id;
    private Estados estados;
    private Peticiones peticiones;

    public HistoricoPeticiones() {
    }

    public HistoricoPeticiones(int id, Estados estados, Peticiones peticiones) {
        this.id = id;
        this.estados = estados;
        this.peticiones = peticiones;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_estado", nullable = false)
    public Estados getEstados() {
        return this.estados;
    }

    public void setEstados(Estados estados) {
        this.estados = estados;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_peticion", nullable = false)
    public Peticiones getPeticiones() {
        return this.peticiones;
    }

    public void setPeticiones(Peticiones peticiones) {
        this.peticiones = peticiones;
    }

}
