package es.bgtiban.infrastructure.persistence.jpa.entity;
// Generated 6 sept 2022 12:48:20 by Hibernate Tools 5.2.13.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HistoricoPeticionesRelRedesId generated by hbm2java
 */
@Embeddable
public class HistoricoPeticionesRelRedesId implements java.io.Serializable {

    private int idHistoricoPeticion;
    private int idRed;

    public HistoricoPeticionesRelRedesId() {
    }

    public HistoricoPeticionesRelRedesId(int idHistoricoPeticion, int idRed) {
        this.idHistoricoPeticion = idHistoricoPeticion;
        this.idRed = idRed;
    }

    @Column(name = "id_historico_peticion", nullable = false)
    public int getIdHistoricoPeticion() {
        return this.idHistoricoPeticion;
    }

    public void setIdHistoricoPeticion(int idHistoricoPeticion) {
        this.idHistoricoPeticion = idHistoricoPeticion;
    }

    @Column(name = "id_red", nullable = false)
    public int getIdRed() {
        return this.idRed;
    }

    public void setIdRed(int idRed) {
        this.idRed = idRed;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof HistoricoPeticionesRelRedesId))
            return false;
        HistoricoPeticionesRelRedesId castOther = (HistoricoPeticionesRelRedesId) other;

        return (this.getIdHistoricoPeticion() == castOther.getIdHistoricoPeticion())
                && (this.getIdRed() == castOther.getIdRed());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdHistoricoPeticion();
        result = 37 * result + this.getIdRed();
        return result;
    }

}
