package es.bgtiban.infrastructure.persistence.jpa.entity;
// Generated 6 sept 2022 12:48:20 by Hibernate Tools 5.2.13.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistoricoPeticionesRelRedes generated by hbm2java
 */
@Entity
@Table(name = "historico_peticiones_rel_redes")
public class HistoricoPeticionesRelRedes implements java.io.Serializable {

    private HistoricoPeticionesRelRedesId id;
    private Peticiones peticiones;
    private Redes redes;
    private Date fechaPeticion;

    public HistoricoPeticionesRelRedes() {
    }

    public HistoricoPeticionesRelRedes(HistoricoPeticionesRelRedesId id, Peticiones peticiones, Redes redes) {
        this.id = id;
        this.peticiones = peticiones;
        this.redes = redes;
    }

    public HistoricoPeticionesRelRedes(HistoricoPeticionesRelRedesId id, Peticiones peticiones, Redes redes,
            Date fechaPeticion) {
        this.id = id;
        this.peticiones = peticiones;
        this.redes = redes;
        this.fechaPeticion = fechaPeticion;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "idHistoricoPeticion", column = @Column(name = "id_historico_peticion", nullable = false)),
            @AttributeOverride(name = "idRed", column = @Column(name = "id_red", nullable = false)) })
    public HistoricoPeticionesRelRedesId getId() {
        return this.id;
    }

    public void setId(HistoricoPeticionesRelRedesId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_historico_peticion", nullable = false, insertable = false, updatable = false)
    public Peticiones getPeticiones() {
        return this.peticiones;
    }

    public void setPeticiones(Peticiones peticiones) {
        this.peticiones = peticiones;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_red", nullable = false, insertable = false, updatable = false)
    public Redes getRedes() {
        return this.redes;
    }

    public void setRedes(Redes redes) {
        this.redes = redes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_peticion", length = 29)
    public Date getFechaPeticion() {
        return this.fechaPeticion;
    }

    public void setFechaPeticion(Date fechaPeticion) {
        this.fechaPeticion = fechaPeticion;
    }

}
