package es.bgtiban.infrastructure.persistence.jpa.entity;
// Generated 6 sept 2022 12:48:20 by Hibernate Tools 5.2.13.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PeticionesRelCuentas generated by hbm2java
 */
@Entity
@Table(name = "peticiones_rel_cuentas")
public class PeticionesRelCuentas implements java.io.Serializable {

    private PeticionesRelCuentasId id;
    private Cuentas cuentas;
    private Peticiones peticiones;
    private Date fechaPeticion;

    public PeticionesRelCuentas() {
    }

    public PeticionesRelCuentas(PeticionesRelCuentasId id, Cuentas cuentas, Peticiones peticiones, Date fechaPeticion) {
        this.id = id;
        this.cuentas = cuentas;
        this.peticiones = peticiones;
        this.fechaPeticion = fechaPeticion;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "idPeticion", column = @Column(name = "id_peticion", nullable = false)),
            @AttributeOverride(name = "idCuenta", column = @Column(name = "id_cuenta", nullable = false, length = 50)) })
    public PeticionesRelCuentasId getId() {
        return this.id;
    }

    public void setId(PeticionesRelCuentasId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_cuenta", nullable = false, insertable = false, updatable = false)
    public Cuentas getCuentas() {
        return this.cuentas;
    }

    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_peticion", nullable = false, insertable = false, updatable = false)
    public Peticiones getPeticiones() {
        return this.peticiones;
    }

    public void setPeticiones(Peticiones peticiones) {
        this.peticiones = peticiones;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_peticion", nullable = false, length = 29)
    public Date getFechaPeticion() {
        return this.fechaPeticion;
    }

    public void setFechaPeticion(Date fechaPeticion) {
        this.fechaPeticion = fechaPeticion;
    }

}
