package es.bgtiban.infrastructure.persistence.jpa.entity;
// Generated 6 sept 2022 12:48:20 by Hibernate Tools 5.2.13.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PeticionesRelCuentasId generated by hbm2java
 */
@Embeddable
public class PeticionesRelCuentasId implements java.io.Serializable {

    private int idPeticion;
    private String idCuenta;

    public PeticionesRelCuentasId() {
    }

    public PeticionesRelCuentasId(int idPeticion, String idCuenta) {
        this.idPeticion = idPeticion;
        this.idCuenta = idCuenta;
    }

    @Column(name = "id_peticion", nullable = false)
    public int getIdPeticion() {
        return this.idPeticion;
    }

    public void setIdPeticion(int idPeticion) {
        this.idPeticion = idPeticion;
    }

    @Column(name = "id_cuenta", nullable = false, length = 50)
    public String getIdCuenta() {
        return this.idCuenta;
    }

    public void setIdCuenta(String idCuenta) {
        this.idCuenta = idCuenta;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof PeticionesRelCuentasId))
            return false;
        PeticionesRelCuentasId castOther = (PeticionesRelCuentasId) other;

        return (this.getIdPeticion() == castOther.getIdPeticion())
                && ((this.getIdCuenta() == castOther.getIdCuenta()) || (this.getIdCuenta() != null
                        && castOther.getIdCuenta() != null && this.getIdCuenta().equals(castOther.getIdCuenta())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdPeticion();
        result = 37 * result + (getIdCuenta() == null ? 0 : this.getIdCuenta().hashCode());
        return result;
    }

}
