package es.bgtiban.infrastructure.persistence.jpa.entity;
// Generated 6 sept 2022 12:48:20 by Hibernate Tools 5.2.13.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Redes generated by hbm2java
 */
@Entity
@Table(name = "redes", uniqueConstraints = @UniqueConstraint(columnNames = "red_social"))
public class Redes implements java.io.Serializable {

    private int id;
    private String nick;
    private String redSocial;
    private String descripcion;
    private Set historicoPeticionesRelRedeses = new HashSet(0);

    public Redes() {
    }

    public Redes(int id, String nick, String redSocial, String descripcion) {
        this.id = id;
        this.nick = nick;
        this.redSocial = redSocial;
        this.descripcion = descripcion;
    }

    public Redes(int id, String nick, String redSocial, String descripcion, Set historicoPeticionesRelRedeses) {
        this.id = id;
        this.nick = nick;
        this.redSocial = redSocial;
        this.descripcion = descripcion;
        this.historicoPeticionesRelRedeses = historicoPeticionesRelRedeses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nick", nullable = false, length = 50)
    public String getNick() {
        return this.nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    @Column(name = "red_social", unique = true, nullable = false, length = 20)
    public String getRedSocial() {
        return this.redSocial;
    }

    public void setRedSocial(String redSocial) {
        this.redSocial = redSocial;
    }

    @Column(name = "descripcion", nullable = false, length = 200)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "redes")
    public Set getHistoricoPeticionesRelRedeses() {
        return this.historicoPeticionesRelRedeses;
    }

    public void setHistoricoPeticionesRelRedeses(Set historicoPeticionesRelRedeses) {
        this.historicoPeticionesRelRedeses = historicoPeticionesRelRedeses;
    }

}
