package es.bgtiban.infrastructure.persistence.jpa.entity;
// Generated 6 sept 2022 12:48:20 by Hibernate Tools 5.2.13.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ubicaciones generated by hbm2java
 */
@Entity
@Table(name = "ubicaciones")
public class Ubicaciones implements java.io.Serializable {

    private int id;
    private String latitud;
    private String longitud;
    private String altitud;
    private String tipoVia;
    private String numero;
    private String piso;
    private String puerta;
    private Set peticioneses = new HashSet(0);

    public Ubicaciones() {
    }

    public Ubicaciones(int id, String latitud, String longitud, String altitud, String tipoVia) {
        this.id = id;
        this.latitud = latitud;
        this.longitud = longitud;
        this.altitud = altitud;
        this.tipoVia = tipoVia;
    }

    public Ubicaciones(int id, String latitud, String longitud, String altitud, String tipoVia, String numero,
            String piso, String puerta, Set peticioneses) {
        this.id = id;
        this.latitud = latitud;
        this.longitud = longitud;
        this.altitud = altitud;
        this.tipoVia = tipoVia;
        this.numero = numero;
        this.piso = piso;
        this.puerta = puerta;
        this.peticioneses = peticioneses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "latitud", nullable = false, length = 100)
    public String getLatitud() {
        return this.latitud;
    }

    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    @Column(name = "longitud", nullable = false, length = 100)
    public String getLongitud() {
        return this.longitud;
    }

    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    @Column(name = "altitud", nullable = false, length = 100)
    public String getAltitud() {
        return this.altitud;
    }

    public void setAltitud(String altitud) {
        this.altitud = altitud;
    }

    @Column(name = "tipo_via", nullable = false, length = 30)
    public String getTipoVia() {
        return this.tipoVia;
    }

    public void setTipoVia(String tipoVia) {
        this.tipoVia = tipoVia;
    }

    @Column(name = "numero", length = 10)
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @Column(name = "piso", length = 10)
    public String getPiso() {
        return this.piso;
    }

    public void setPiso(String piso) {
        this.piso = piso;
    }

    @Column(name = "puerta", length = 10)
    public String getPuerta() {
        return this.puerta;
    }

    public void setPuerta(String puerta) {
        this.puerta = puerta;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ubicaciones")
    public Set getPeticioneses() {
        return this.peticioneses;
    }

    public void setPeticioneses(Set peticioneses) {
        this.peticioneses = peticioneses;
    }

}
