openapi: 3.0.2
info:
  title: Api contract for stock.
  description: Api contract to manage stock
  termsOfService: none
  contact:
    email: bryan.tiban@blabla.blabla
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
servers:
- url: https://stock.es/v1/
tags:
- name: ApiStock
  description: Operations on the stock
paths:
  /stock/prices:
    get:
      tags:
      - ApiStock
      summary: Search prices products.
      description: Obtains information about the prices being applied to the products passed by parameter.
      operationId: searchPrices
      parameters:
      - name: applicationDate
        in: query
        description: Date on which the discount is applied
        required: true
        schema:
          type: string
          pattern: '^\d{4}-[01]\d-[0-3]\d-[0-2]\d.[0-5]\d.[0-5]\d$'
          example: 2020-06-14-00.00.00
      - name: product-id
        in: query
        description: Id assigned to the product.
        required: true
        schema:
          type: string
          example: 1 
          pattern: '^[0-9]{1,15}$'
      - name: brand-id
        in: query
        description: Id assigned to the brand
        required: true
        schema:
          type: string
          pattern: '^[0-9]{1,15}$'
          example: 1
      responses:
        200:
          description: ApiLocation information recovered succesfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiResponseSearchPrice'
components:
  schemas:
    ApiResponseSearchPrice:
      type: object
      properties:
        product-id:
          type: string
          description: product id.
          example: 1
        brand-id:
          type: string
          description: brand id.
          example: 1
        rate-id:
          type: string
          description: rate id.
          example: 1
        start-date:
          type: string
          description: Starting date on which the indicated rate is applied
          example: 2020-06-14-00.00.00
        end-date:
          type: string
          description: Final date on which the indicated rate is applied
          example: 2020-12-31-23.59.59
        price:
          type: number
          description: final price of product
          example: 35.5