
CREATE TABLE prices(
	ID BIGINT auto_increment,
	BRAND_ID BIGINT,
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	PRICE_LIST BIGINT,
	PRODUCT_ID BIGINT,
	PRIORITY NUMERIC,
	PRICE NUMERIC,
	CURR VARCHAR(3)
);